elasticsearch:
  build: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - /var/opt/risno/elastic-storage/log/:/var/log/elasticsearch
    - /var/opt/risno/elastic-storage/data/:/var/lib/elasticsearch

node:
  build: nodejs
  volumes:
    - /opt/risno/:/opt/risno
  ports:
    - "12043:12043"
  links:
    - elasticsearch
