elasticsearch:
  image: pgrange/elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - /opt/risno/elastic-storage/log/:/var/log/elasticsearch
    - /opt/risno/elastic-storage/data/:/var/lib/elasticsearch

web:
  build: nodejs
  volumes:
    - /opt/risno/:/opt/risno
  ports:
    - "12043:12043"
  # links:
  #   - elasticsearch
